### ISSUE TITLE
用户名过长时 `发私信` 和 `关注` 按钮位置有些奇怪

### ISSUE THREAD

**Issue by Geeyun-JY3** [wTonyChen/flatnmusic#10]
**描述问题**
用户名过长时 `发私信` 和 `关注` 按钮位置有些奇怪

**截图（可选）**
[![image](https://user-images.githubusercontent.com/49396421/94336563-d6535c80-0016-11eb-94a3-f72a133b6ef1.png)](https://music.163.com/#/user?id=51548361)
对比
![image](https://user-images.githubusercontent.com/49396421/94336917-3519d580-0019-11eb-9726-a337c43540a6.png)
![image](https://user-images.githubusercontent.com/49396421/94336858-d6ecf280-0018-11eb-99de-86cb37eb9a4d.png)
![image](https://user-images.githubusercontent.com/49396421/94336789-50d0ac00-0018-11eb-9630-b66cbb918321.png)

**桌面端**
 - 操作系统：
 - 浏览器：Chrome（百分浏览器）
 - 浏览器版本：百分浏览器 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
 - 显示分辨率：1920x1080
 - 工具：Stylus

**Comment by wTonyChen** [comment]
谢谢提醒更新😆

现在新版本已经推出，问题可能已经修复。如果问题已经修复，您可自行关闭此 Issue。

[更新链接](https://wtonychen.github.io/flatnmusic/flatnmusic.user.css) | [Greasy Fork](https://greasyfork.org/scripts/406821)

感谢支持 :)

**Comment by Geeyun-JY3** [comment]
问题依然存在

**Comment by wTonyChen** [comment]
> 问题依然存在

现在新版本已经推出，以更进一步修复此问题。

[更新链接](https://wtonychen.github.io/flatnmusic/flatnmusic.user.css) | [Greasy Fork](https://greasyfork.org/scripts/406821)

如果问题已经修复，您可自行关闭此 Issue。

感谢支持 :)

**Comment by Geeyun-JY3** [comment]
顺便一提，[404 页](https://music.163.com/#/404) 是不是也忘了适配

**Comment by wTonyChen** [comment]
> 顺便一提，[404 页](https://music.163.com/#/404) 是不是也忘了适配

404 页的支持已经在0.7.10版本加上了😁

**Comment by Geeyun-JY3** [comment]
OK 了

**Comment by Geeyun-JY3** [comment]
不过我觉得在上述用户名过长的情况下可以用弹出个 tooltip 来显示完整用户名，或者干脆给所有用户都加上这么个 tooltip（样式做不到当我没说🙈）

**Comment by wTonyChen** [comment]
> 不过我觉得在上述用户名过长的情况下可以用弹出个 tooltip 来显示完整用户名，或者干脆给所有用户都加上这么个 tooltip（样式做不到当我没说🙈）

样式确实做不到这样的修改，所以才有了辅助脚本的存在啊😂

**Comment by Geeyun-JY3** [comment]
> 样式确实做不到这样的修改，所以才有了辅助脚本的存在啊😂

那用脚本试试🙈？

**Comment by wTonyChen** [comment]
> > 样式确实做不到这样的修改，所以才有了辅助脚本的存在啊😂
> 
> 那用脚本试试🙈？

好的，我会试着在下个版本的辅助脚本加入这个功能😊

**Comment by wTonyChen** [comment]
> > > 样式确实做不到这样的修改，所以才有了辅助脚本的存在啊😂
> > 
> > 
> > 那用脚本试试🙈？
> 
> 好的，我会试着在下个版本的辅助脚本加入这个功能😊

在样式表 0.7.11 / 辅助脚本 0.1.4-0.7.11 版本已经为用户资料页面的用户名添加悬浮展开和工具提示，
可以将样式表和辅助脚本更新到最新版本来体验此功能。

有欢迎提出任何建议和改进意见，
感谢支持😁

**Comment by Geeyun-JY3** [comment]
具体效果是怎样的呢，能不能截图看一下？我这边试了试好像不行。

**Comment by wTonyChen** [comment]
> 具体效果是怎样的呢，能不能截图看一下？我这边试了试好像不行。

将鼠标悬浮于用户名之上即可看到长用户名和完整名称的工具提示

<img width="605" alt="0-09 211738" src="https://user-images.githubusercontent.com/12113817/95587725-0538ec00-0a75-11eb-9bd6-f7d11f210c8c.png">

**Comment by Geeyun-JY3** [comment]
我 issue 里 [第一个截图的歌手](https://music.163.com/#/user?id=51548361) 就不行啊。
![image](https://user-images.githubusercontent.com/49396421/95588723-5695ab00-0a76-11eb-9fc9-6a1113384eca.png)

**Comment by wTonyChen** [comment]
> 我 issue 里 [第一个截图的歌手](https://music.163.com/#/user?id=51548361) 就不行啊。
> ![image](https://user-images.githubusercontent.com/49396421/95588723-5695ab00-0a76-11eb-9fc9-6a1113384eca.png)

使用此功能需要同时安装不低于0.1.4-0.7.11版本的辅助脚本和0.7.11版本的样式表，辅助脚本需要处于启用状态。

如果辅助脚本已经启用，请在右上角头像-个人设置中的页面应会出现辅助脚本设置和相应的版本号，如下图所示：
<img width="826" alt="648" src="https://user-images.githubusercontent.com/12113817/95589638-95783080-0a77-11eb-81c8-9e2ff68f6a77.png">

**Comment by Geeyun-JY3** [comment]
![image](https://user-images.githubusercontent.com/49396421/95590167-4979bb80-0a78-11eb-8277-8291172103ea.png)

**Comment by wTonyChen** [comment]
实测，百分浏览器是完全没有问题的
版本 4.2.10.171 / Chromium 80.0.3987.163
用户脚本扩展：Tampermonkey 4.10  /  0.1.4-0.7.11 辅助脚本
用户样式扩展：Stylus 1.5.13  /  0.7.11 样式表
请检查是不是出现了脚本或者样式的冲突，或者是否安装了兼容的扩展程序。

![image](https://user-images.githubusercontent.com/12113817/95592441-32889880-0a7b-11eb-9d68-969e7b652721.png)

**Comment by Geeyun-JY3** [comment]
额和百分浏览器没关系，上面我也已经在 Chrome 86.0.4240.75 中测试过，也是这么个情况。

在 Chrome 86.0.4240.75 中，我已经把其他所有插件脚本都关了，也清了一遍缓存，还是这么个情况：
![image](https://user-images.githubusercontent.com/49396421/95599402-9adb7800-0a83-11eb-9db9-596b68ad829f.png)

**Comment by wTonyChen** [comment]
> 额和百分浏览器没关系，上面我也已经在 Chrome 86.0.4240.75 中测试过，也是这么个情况。
> 
> 在 Chrome 86.0.4240.75 中，我已经把其他所有插件脚本都关了，也清了一遍缓存，还是这么个情况：
> ![image](https://user-images.githubusercontent.com/49396421/95599402-9adb7800-0a83-11eb-9db9-596b68ad829f.png)

请问一下您所使用的用户脚本扩展是什么？辅助脚本主要针对Tampermonkey适配。如果使用的不是Tampermonkey，可以尝试在Tampermonkey中安装此辅助脚本，再看看问题是否解决。

**Comment by Geeyun-JY3** [comment]
啊这
我这截图里的图标不就是 Tampermonkey 吗🌝

**Comment by wTonyChen** [comment]
> 额和百分浏览器没关系，上面我也已经在 Chrome 86.0.4240.75 中测试过，也是这么个情况。
> 
> 在 Chrome 86.0.4240.75 中，我已经把其他所有插件脚本都关了，也清了一遍缓存，还是这么个情况：
> ![image](https://user-images.githubusercontent.com/49396421/95599402-9adb7800-0a83-11eb-9db9-596b68ad829f.png)

我注意到您总共启用了2个用户脚本和2个样式表，您有试过禁用其余的样式表或用户脚本并刷新页面吗

**Comment by Geeyun-JY3** [comment]
> 我注意到您总共启用了2个用户脚本和2个样式表

图中开启另一个样式是 [全局思源黑体](http://userstyles.org/styles/123597)，关了之后没区别：
![image](https://user-images.githubusercontent.com/49396421/95646097-994b9780-0af7-11eb-9188-2607941610a9.png)

工具栏图标显示「2」是因为我在设置项 `图标徽章信息` 中选择的是「运行的脚本实例」：
设置项：
![image](https://user-images.githubusercontent.com/49396421/95646114-cf891700-0af7-11eb-951f-83a56e38c71e.png)
实际上 Tampermonkey 里只有一个脚本：
![image](https://user-images.githubusercontent.com/49396421/95646125-e7f93180-0af7-11eb-8418-f4b4054d02c4.png)

**Comment by Geeyun-JY3** [comment]
> ![image](https://user-images.githubusercontent.com/12113817/95592441-32889880-0a7b-11eb-9d68-969e7b652721.png)
>
> <img alt="0-09 211738" width="605" src="https://user-images.githubusercontent.com/12113817/95587725-0538ec00-0a75-11eb-9bd6-f7d11f210c8c.png">

我看你两张有效的截图中都没显示用户等级、性别、黑胶年会员的信息，会不会和这个有关。

**Comment by wTonyChen** [comment]
> > ![image](https://user-images.githubusercontent.com/12113817/95592441-32889880-0a7b-11eb-9d68-969e7b652721.png)
> > <img alt="0-09 211738" width="605" src="https://user-images.githubusercontent.com/12113817/95587725-0538ec00-0a75-11eb-9bd6-f7d11f210c8c.png">
> 
> 我看你两张有效的截图中都没显示用户等级、性别、黑胶年会员的信息，会不会和这个有关。

将鼠标悬浮在用户名后，用户名旁边的信息会隐藏，目的是为用户名腾出更多显示空间。
现在新版本的用户样式和脚本已经更新，已经改进了触发行为。在更新0.1.5-0.7.12版本后，请在**辅助脚本设置**中手动勾选`使用样式表的增强外观`。

如果此修复对您还没有生效，那么可能不会继续为此问题提供修复。
您可以尝试使用全新安装的浏览器测试，以上使用的测试是百分浏览器32位的全新安装。

感谢支持和反馈😊

**Comment by Geeyun-JY3** [comment]
啊在全新的 Edge 里测试也还是这样啊，用户名旁边的信息不会隐藏，不会触发任何动作啊（悲

**Comment by Geeyun-JY3** [comment]
补充一些测试效果：用户名不长的用户个人主页是可以生效的，但就是 [肥皂菌丨珉珉的猫咪丨](https://music.163.com/user?id=51548361) 无效果。这个例子可能比较极端，需要同时满足用户名过长、歌手、黑胶 VIP，但我还找到一个也满足这两个条件的歌手：[该用户名包含敏感字](https://music.163.com/user?id=295648808)，脚本也是可以生效的。
不会是和 `肥皂菌丨珉珉的猫咪丨` 这个用户名中的字符有关系吧。。。

还有，鼠标悬浮于用户名之上后对用户名进行选中文字操作，看不见光标和已选中文字。

**Comment by Geeyun-JY3** [comment]
好像可以了……好像在其他用户个人主页触发一次后就可以了……具体这样是不是真的能复现我也不太确定（记忆混乱

**Comment by wTonyChen** [comment]
> 好像可以了……好像在其他用户个人主页触发一次后就可以了……具体这样是不是真的能复现我也不太确定（记忆混乱

感谢提供链接，已经找到问题所在了，是链接路径的判断末尾多了个斜杠，你现在可以尝试将 *** /user? *** 改为 *** /user/? ***

即将推出一个修复更新来修复此问题。

**Comment by Geeyun-JY3** [comment]
> 是链接路径的判断末尾多了个斜杠

啊这……是链接的问题吗……
好像网易这个 URL 特别迷，将最终跳转的 URL 中一些地方的斜杠（还有那个 `#`）删去结果都是一样的（还不会统一跳转至一个 URL）。
