### ISSUE TITLE
[BUG] 播放器无法正常的移动进度条

### ISSUE THREAD

**Issue by a6513375** [wTonyChen/flatnmusic#11]
播放器无法正常的移动进度条

视频:https://m2bt.lanzous.com/ihNUgh38gmb

 - 操作系统 Windows 10 1909
 - 浏览器 Chrome 
 - 浏览器版本 85.0.4183.121 64-bit
 - 显示分辨率 1920x1080
 - 工具 Stylus

**Comment by wTonyChen** [comment]
已经收到反馈，正在调查原因

**Comment by wTonyChen** [comment]
> 已经收到反馈，正在调查原因

已知应用样式后，点击进度条会跳至音乐开头，移动进度条圆点功能未受影响。
目前正在确定具体影响此功能的代码，如果有任何进展，将会在此 Issue 中进行更新。

感谢反馈和支持 😁

**Comment by wTonyChen** [comment]
> > 已经收到反馈，正在调查原因
> 
> 已知应用样式后，点击进度条会跳至音乐开头，移动进度条圆点功能未受影响。
> 目前正在确定具体影响此功能的代码，如果有任何进展，将会在此 Issue 中进行更新。
> 

在样式表 0.7.11 版本已经修复进度条的异常行为，
可以将样式表更新到最新版本来获得修复。

如果问题已经修复，您可以自行关闭此 Issue。

有欢迎提出任何建议和改进意见，
感谢支持😁
