### ISSUE TITLE
歌单／专辑（歌曲列表）中高亮正在播放的歌曲的播放按钮

### ISSUE THREAD

**Issue by Geeyun-JY3** [wTonyChen/flatnmusic#12]
**描述你所想的解决方案**
歌单／专辑（歌曲列表）中高亮正在播放的歌曲的播放按钮，像原版效果一样。

**附加内容（可选）**
原版效果：
![image](https://user-images.githubusercontent.com/49396421/95576245-b4b89300-0a62-11eb-9d2c-95643bf9b13c.png)

**Comment by wTonyChen** [comment]
改进建议已经收到，可能会在下个版本中推出改进后的播放按钮。

**Comment by wTonyChen** [comment]
样式表 0.7.15 版本已经改进了列表播放按钮，如果觉得还满意话，您可以自行关闭此 Issue

感谢支持😊
