### ISSUE TITLE
通过底栏进度条链接图标跳转至歌单／专辑（歌曲列表）该歌曲位置时锚点定位错误

### ISSUE THREAD

**Issue by Geeyun-JY3** [wTonyChen/flatnmusic#13]
**描述问题**
播放歌单／专辑（歌曲列表）歌曲时，通过底栏进度条链接图标跳转至歌单／专辑（歌曲列表）该歌曲位置时锚点定位错误。

我这边测试跳转后的位置在目标位置的下方，可能差了一个顶栏的高度；且跳转完成后关闭样式顶部刚好对齐歌曲列表中目标歌曲的下一首歌（这一段看懂了吗/汗）。

**截图（可选）**
底栏进度条链接图标
![image](https://user-images.githubusercontent.com/49396421/95577617-17ab2980-0a65-11eb-8177-50eeb7699626.png)

官方跳转完成效果：
![image](https://user-images.githubusercontent.com/49396421/95579472-4676cf00-0a68-11eb-8cad-ed4cae74273e.png)

**桌面端**
 - 操作系统：
 - 浏览器：Chrome（百分浏览器）
 - 浏览器版本：百分浏览器 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
 - 显示分辨率：1920x1080
 - 工具：Stylus

**Comment by wTonyChen** [comment]
很抱歉，此问题将不能进行修复，如果此问题影响了使用体验，则建议将**顶栏滚动状态**设置为`跟随页面滚动`。

此 Issue 将会关闭，欢迎提出更多建议或改进意见，感谢支持😊

**Comment by Geeyun-JY3** [comment]
确实是 `顶栏滚动状态` 这个设置项选择了 `固定于顶栏` 后才会出现此 bug。
既然如此好的吧。
