### ISSUE TITLE
搜索结果页用户 tab 关注按钮未适配

### ISSUE THREAD

**Issue by Geeyun-JY3** [wTonyChen/flatnmusic#14]
**描述问题**
搜索结果页用户 tab 关注按钮未适配

**截图（可选）**
![image](https://user-images.githubusercontent.com/49396421/95681116-a90acf00-0c10-11eb-91eb-9f3c3b17c650.png)

**桌面端**
 - 操作系统：
 - 浏览器：Chrome（百分浏览器）
 - 浏览器版本：百分浏览器 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
 - 显示分辨率：1920x1080
 - 工具：Stylus

**Comment by wTonyChen** [comment]
感谢反馈，改进建议已经收到，可能会在下个大版本中推出此内容。

**Comment by wTonyChen** [comment]
样式表 0.7.15 版本已经添加了此样式，如果觉得还满意话，您可以自行关闭此 Issue

感谢支持😊
