### ISSUE TITLE
适配「用户wiki」页

### ISSUE THREAD

**Issue by Geeyun-JY3** [wTonyChen/flatnmusic#15]
**描述你所想的解决方案**
适配「用户wiki」页，详见这篇专栏文章：https://music.163.com/#/topic?id=43505267
示例：https://music.163.com/#/wiki/song?songId=28457932

**Comment by wTonyChen** [comment]
反馈已经收到，因为某些原因，可能需要晚一点更新，感谢支持😊

**Comment by wTonyChen** [comment]
样式表 0.8.0 版本已经修复，如果觉得还满意话，您可以自行关闭此 Issue

感谢支持😊
