### ISSUE TITLE
适配用户分享的跳转结果页

### ISSUE THREAD

**Issue by Geeyun-JY3** [wTonyChen/flatnmusic#16]
**描述你所想的解决方案**
适配用户分享的跳转结果页
如：https://music.163.com/#/share/sina/direct/18/1498656272?userid=268800588&haspic=0&app_version=7.3.50
能在顶部看到「xxx 分享给你一个单曲」。
应该不只有歌曲有这个效果。

**Comment by wTonyChen** [comment]
反馈已经收到，因为某些原因，可能需要晚一点更新，感谢支持😊

**Comment by wTonyChen** [comment]
样式表 0.8.0 版本已经修复，如果觉得还满意话，您可以自行关闭此 Issue

感谢支持😊
