### ISSUE TITLE
几个未适配元素反馈

### ISSUE THREAD

**Issue by Geeyun-JY3** [wTonyChen/flatnmusic#17]
**描述问题**
几个未适配元素
VIP 单曲（见图 1）
底栏播放器的播放列表中的歌曲的来源图标（见图 2、3）

**截图（可选）**
VIP 单曲标签和播放按钮
![image](https://user-images.githubusercontent.com/49396421/102693611-c4b8d400-4256-11eb-8b03-52d4037b9c13.png)

底栏播放器的播放列表中的歌曲无法区分是否有来源：
![image](https://user-images.githubusercontent.com/49396421/102693634-fe89da80-4256-11eb-98f6-c1be3350a5a1.png)
以下是原版效果（有明暗效果进行区分的）：
![image](https://user-images.githubusercontent.com/49396421/102693756-e4043100-4257-11eb-8633-06e9d4571238.png)

**桌面端**
 - 操作系统：Windows 20H2 19042.685
 - 浏览器：Chrome（百分浏览器）
 - 浏览器版本：百分浏览器 4.3.9.227（正式版本） （64 位） (Chromium 86.0.4240.198)
 - 显示分辨率：1920x1080
 - 工具：Stylus

**Comment by wTonyChen** [comment]
反馈已经收到，因为某些原因，可能需要晚一点更新，感谢支持😊

**Comment by wTonyChen** [comment]
样式表 0.8.0 版本已经修复，如果觉得还满意话，您可以自行关闭此 Issue

感谢支持😊

**Comment by Geeyun-JY3** [comment]
扣个小细节，「暂无来源」的 tooltip 好像没掉了。

突然觉得发现这个 VIP 下载的按钮，建议也做个适配。
![image](https://user-images.githubusercontent.com/49396421/102839756-330abb80-443c-11eb-8d0e-74eafb2d1ad1.png)

**Comment by Geeyun-JY3** [comment]
还有未登录状态下的 `开通 VIP 畅听` 按钮有些小问题：
![image](https://user-images.githubusercontent.com/49396421/102840193-466a5680-443d-11eb-8ade-535a765ba963.png)

**Comment by wTonyChen** [comment]
样式表 0.8.1 版本已经修复“开通 VIP 畅听”按钮的问题
由于并没有出现未预期的显示效果，并且没有实际影响使用，所以下载按钮将不会进行任何更改

如果觉得还满意话，您可以自行关闭此 Issue
感谢支持😊

**Comment by Geeyun-JY3** [comment]
「暂无来源」的 tooltip 也不修吗……我觉得这点还是按照原版的效果好，免得有不清楚的用户在这个灰色的图标上点了半天搞不懂为啥没反应

**Comment by wTonyChen** [comment]
> 「暂无来源」的 tooltip 也不修吗……我觉得这点还是按照原版的效果好，免得有不清楚的用户在这个灰色的图标上点了半天搞不懂为啥没反应

0.8.2 已经修复了哦😊

**Comment by Geeyun-JY3** [comment]
> 0.8.2 已经修复了哦😊

啊可能是我这边和别的插件脚本有冲突，我自己排除一下吧。
