### ISSUE TITLE
使顶栏可动态固定

### ISSUE THREAD

**Issue by Geeyun-JY3** [wTonyChen/flatnmusic#19]
**这个功能请求是否与问题关联？请描述。（可选）**
勉强算是 #13 的一个替代解决方案

**描述你所想的解决方案**
`顶栏滚动状态` 增加一个 `动态固定` 选项。
具体来说就是页面往下滚动时顶栏收起，向上滚动时顶栏固定。可以参考 B 站直播间的顶栏，就是我心中的理想效果。

**附加内容（可选）**
B 站直播间的顶栏效果：
![navbar](https://user-images.githubusercontent.com/49396421/99349624-67d4a180-28d7-11eb-98f5-208515c073ca.gif)

**Comment by wTonyChen** [comment]
在样式表 0.8.5、辅助脚本0.2.0-0.8.5中已经添加了此功能。
将样式表和辅助脚本同时更新到最新版本，然后在个人设置中勾选`使用动态固定的顶栏`，然后刷新页面即可。

如果您对改进满意的话，则可以关闭此 Issue。

感谢支持😊

**Comment by Geeyun-JY3** [comment]
效果总体上来说很棒，就是每次都要等页面加载一会该效果才会完全生效。是本就如此还是 Tampermonkey 设置项的问题？

另外建议顶栏不要挡住右边的滚动条。

**Comment by wTonyChen** [comment]
> 效果总体上来说很棒，就是每次都要等页面加载一会该效果才会完全生效。是本就如此还是 Tampermonkey 设置项的问题？
> 
> 另外建议顶栏不要挡住右边的滚动条。

很抱歉，因为网易云音乐页面结构的限制，顶栏在固定的情况下是必须要盖住滚动条。

**Comment by Geeyun-JY3** [comment]
> 很抱歉，因为网易云音乐页面结构的限制，顶栏在固定的情况下是必须要盖住滚动条。

这样啊，好的吧。

**Comment by Geeyun-JY3** [comment]
那每次都要等页面加载一会该效果才会完全生效有办法优化吗？

**Comment by wTonyChen** [comment]
> 那每次都要等页面加载一会该效果才会完全生效有办法优化吗？

目前这个功能还处于 Beta 版，仍有很多需要完善的地方，敬请谅解😊

**Comment by wTonyChen** [comment]
> 那每次都要等页面加载一会该效果才会完全生效有办法优化吗？

现已更新 0.2.2-0.8.8 和 0.8.8 版本，改进了顶栏重置的机制，请同时将样式表和辅助脚本更新至最新版本并刷新浏览器看到更改。

**Comment by Geeyun-JY3** [comment]
> 目前这个功能还处于 Beta 版，仍有很多需要完善的地方，敬请谅解😊

👌
