### ISSUE TITLE
歌手的收藏按钮无法区分“已收藏”和“未收藏”

### ISSUE THREAD

**Issue by outloudvi** [wTonyChen/flatnmusic#2]
**描述问题**
无法区分已收藏歌手和未收藏歌手。

**附加内容**
测试了一下，就页面而言，被收藏的歌手按钮会新增一个 class `btnfav-0`。看到 css 中并没有这个类，可能网易云最近又改版了什么的...

**Comment by wTonyChen** [comment]
0.3.91更新已修复无法区分歌手收藏状态的问题

更新地址：https://raw.githubusercontent.com/wTonyChen/flatnmusic/master/flatnmusic.user.css


感谢支持😊
