### ISSUE TITLE
用户粉丝、关注 tab 下的关注按钮未适配

### ISSUE THREAD

**Issue by Geeyun-JY3** [wTonyChen/flatnmusic#20]
> 简体中文

**描述问题**
用户粉丝、关注 tab 下的关注按钮未适配

**截图（可选）**
![image](https://user-images.githubusercontent.com/49396421/103891759-5f555600-5125-11eb-8656-c827eb62fdbb.png)
![image](https://user-images.githubusercontent.com/49396421/103891822-76944380-5125-11eb-8f56-0e5c887d03d0.png)

**桌面端 (请完成以下信息)**
 - 操作系统：Windows 10 20H2
 - 浏览器：百分浏览器（Chromium）
 - 浏览器版本：4.3.9.248（正式版本） （64 位） (Chromium 86.0.4240.198)
 - 显示分辨率：1920x1080
 - 工具：Stylus

**Comment by wTonyChen** [comment]
反馈已经收到，将会在后续更新补上，感谢反馈和支持😊

**Comment by wTonyChen** [comment]
在样式表 0.8.10 已经改进了此问题。将样式表更新到最新版来查看改进。

如果您对改进满意的话，则可以关闭此 Issue。

感谢支持😊
