### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Tim-Fang** [wTonyChen/flatnmusic#23]
深色模式谢谢  
半夜开网易云还要被白光瞎眼...  
主题色 背景色都改为深色 但不能完全做到深色  
![图片](https://user-images.githubusercontent.com/60050973/112703241-1d8cae00-8ed1-11eb-95f9-fcd95e6feb3f.png)
用插件效果也不好

**Comment by wTonyChen** [comment]
您好，其实暗色模式已经在做了呢

可能还需要再等一段时间哦

感谢支持😊

**Comment by wTonyChen** [comment]
测试版的深色模式已经在 *0.9.2* 的版本推出了

将样式表更新到 *0.9.2* 以上版本即可看到`界面颜色`选项

因为目前仍处在测试阶段，所以可能会出现颜色可见度低或者颜色混乱等问题哦，欢迎对此进行反馈

感谢支持😊

**Comment by Geeyun-JY3** [comment]
0.9.2 这个 `界面颜色` 选项……现在这种实现方式好像不是那种开箱即用一键切换的 Dark Mode……至少还得设置个背景色

**Comment by Tim-Fang** [comment]
还行  
一些没有适配的地方:  
- 登录面板  
- 当开启模糊效果时底部播放栏还是浅色  
- 一些阴影  
- 关闭高对比度文字时一些字是黑色的

**Comment by Tim-Fang** [comment]
aa

**Comment by wTonyChen** [comment]
> 0.9.2 这个 `界面颜色` 选项……现在这种实现方式好像不是那种开箱即用一键切换的 Dark Mode……至少还得设置个背景色

没有将这个选项做成开箱即用，原因是因为想提供更多可供修改的选项，如果大家并不是很喜欢这个选项，我可以考虑在后续的版本中删除`背景色`选项。

**Comment by wTonyChen** [comment]
> 还行
> 一些没有适配的地方:
> 
> * 登录面板
> * 当开启模糊效果时底部播放栏还是浅色
> * 一些阴影
> * 关闭高对比度文字时一些字是黑色的

目前`深色模式`仍处在测试阶段，因为要调色的地方实在是太多了，所以仍有很多地方没有适配。

很抱歉，会在后续的版本中继续改进。

感谢支持😊

**Comment by Geeyun-JY3** [comment]
> > 0.9.2 这个 `界面颜色` 选项……现在这种实现方式好像不是那种开箱即用一键切换的 Dark Mode……至少还得设置个背景色
> 
> 没有将这个选项做成开箱即用，原因是因为想提供更多可供修改的选项，如果大家并不是很喜欢这个选项，我可以考虑在后续的版本中删除`背景色`选项。

倒不是不喜欢，只是我觉得大部分用户以为和习惯的 Dark Mode 肯定不是现在这样。或者说后续将这个 `背景色` 选项拆分成 `深色背景色` 和 `浅色背景色` 两个设置项又或者干脆让`背景色`只会在 `界面元素` 为 `浅色` 时启用，会更靠近用户对  Dark Mode 的一贯认知。

**Comment by wTonyChen** [comment]
由于长时间未回复，此 Issue 将会被关闭。如果您仍有问题，可将此 Issue 重新开启。

**Comment by Geeyun-JY3** [comment]
更新日志没说还不知道。0.9.9 将 `背景色` 选项改成在默认和自定义间选择后，这样的 Dark Mode 应该就符合多数用户对 Dark Mode 的一贯认知了，至少我对这样的实现很满意。
