### ISSUE TITLE
歌词 随机播放等功能键无法正常显示

### ISSUE THREAD

**Issue by famei** [wTonyChen/flatnmusic#24]
![image](https://user-images.githubusercontent.com/61237921/120071641-d6828b00-c0c2-11eb-8a10-6bf604b7fd4d.png)

**Comment by wTonyChen** [comment]
能否提供下您所使用的样式版本号呢？😊

**Comment by famei** [comment]
卧槽光速啊











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wTonyChen/flatnmusic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月29日(星期六) 晚上9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wTonyChen/flatnmusic] 歌词 随机播放等功能键无法正常显示 (#24)





 
能否提供下您所使用的样式版本号呢？😊

**Comment by wTonyChen** [comment]
如果您的样式版本低于 0.9.7 的话，更新一下就可以了哦 😊

**Comment by famei** [comment]
我在github上更新并解决了这个问题&nbsp;
但在https://userstyles.org/ 内并不是最新版本 我在这里下载到了旧版本并遇到了这个错误请作者大大更新一下呀


有一说一这个样式是真的好看 吹爆！！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wTonyChen/flatnmusic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月29日(星期六) 晚上9:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wTonyChen/flatnmusic] 歌词 随机播放等功能键无法正常显示 (#24)





 
如果您的样式版本低于 0.9.7 的话，更新一下就可以了哦 😊

**Comment by wTonyChen** [comment]
很抱歉，主要由于以下原因暂停了 userstyles.org 上的更新：
1. userstyles.org 有 100 KB 的大小限制，现在的样式早已超过 100 KB
2. userstyles.org 的账号登录频繁出现问题
3. userstyles.org 的灵活性并没有 UserCSS 好

综上所述，如果造成不便，我深感抱歉。您可以尝试前往 GreasyFork 或 GitHub 进行下载安装。

感谢支持 😊

**Comment by wTonyChen** [comment]
如果您的问题已经解决，您可以关闭此 Issue 了。
