### ISSUE TITLE
Dark Mode反馈

### ISSUE THREAD

**Issue by a6513375** [wTonyChen/flatnmusic#25]
> 简体中文

**描述问题**
深色模式下的的部分按钮颜色过于奇怪，以及深色模式下的窗口发光为白色，看着也怪怪的

**截图**
![IMG](https://user-images.githubusercontent.com/52791712/124348109-ab87db80-dc1a-11eb-932f-cc8b10de5067.png)

**桌面端 (请完成以下信息)**
 - 操作系统 Windows 10 19042.1052
 - 浏览器 Chrome
 - 浏览器版本  91.0.4472.121 64-bit
 - 显示分辨率 1920x1080
 - 工具 Stylus

**Comment by wTonyChen** [comment]
您好，请问您是否安装了其他样式呢？

如果是，请尝试禁用其他样式。

很抱给您歉造成不便。

**Comment by wTonyChen** [comment]
如果您的主题色设置成黑色，您需要在深色模式下手动设置成非黑色。

**Comment by a6513375** [comment]
> 如果您的主题色设置成黑色，您需要在深色模式下手动设置成非黑色。

主题色更改成白色按钮就正常了 但是窗口发光依然是白色
建议把深色模式的颜色换成(#595959) 太黑了反而不易阅读

还有 脚本设置的自定义样式表弹出的输入框部分文字乱码
![截图](https://user-images.githubusercontent.com/52791712/124351921-d6305f00-dc2f-11eb-9bae-ec4363dc274d.png)

**Comment by wTonyChen** [comment]
1. 窗口发光依然是白色
      - 在深色模式下，所有的边缘都是白色发光，如果您不喜欢这种风格，您可在自定义样式中进行修改。

2. 建议把深色模式的颜色换成(#595959) 太黑了反而不易阅读
      - 在 0.2.11-0.9.11 版本的辅助脚本中添加了 `降低页面对比度` 的选项，以减少较高对比度的视觉冲击。

3. 脚本设置的自定义样式表弹出的输入框部分文字乱码
      - 在 0.2.11-0.9.11 版本的辅助脚本中已经修复此问题，如果此问题仍存在，请在此反馈。

同时，样式表也更新到了 0.9.11 版本，也推荐您更新下。

感谢您的支持😊

**Comment by wTonyChen** [comment]
由于长时间未回复，此 Issue 将会被关闭。如果您仍有问题，可将此 Issue 重新开启。
