### ISSUE TITLE
辅助脚本设置可以放在别的地方嘛

### ISSUE THREAD

**Issue by Luo-Logic** [wTonyChen/flatnmusic#26]
现在它在网易云用户的个人设置里，这对没有网易云账号的人不太友好。一些关键设置，比如查看高清图片都无法打开。

可否将其放在无需登录账号就能访问的界面里？或者使用油猴插件自己的脚本设置？

**Comment by wTonyChen** [comment]
1. 目前还未找到比个人设置页面更适合放置这些设置项目的位置
2. 作者并未在 Greasemonkey 中测试兼容性
3. 目前作者使用的 Tampermonkey 似乎没有添加设置项的功能，为了兼容性的考虑，不会将设置项添加至扩展插件的设置中
4. 辅助脚本设置的部分设置需要登陆或登陆后发挥更佳作用

**Comment by wTonyChen** [comment]
如果有任何想法，想法或者建议，欢迎在此分享

感谢支持😊
