### ISSUE TITLE
能否增加调整界面宽度的选项

### ISSUE THREAD

**Issue by FluereL** [wTonyChen/flatnmusic#28]
如题，目前的默认界面宽度对宽屏环境来说是偏窄的

**Comment by wTonyChen** [comment]
其实这个功能一直在做，而且没有选项可以调整。目前只支持小尺寸，而且只需调整窗口宽度或调整浏览器缩放就可体验到。但是由于网易云音乐的网页版的大多数页面采用了固定宽度，所以也只能进行逐步的适配。

就目前来说，推荐大屏或者宽屏的使用者对页面进行放大使用。设备的性能足够的情况下，能够获得更好的文字渲染效果，和更佳的过渡动画体验。

参考缩放值：
| 屏幕分辨率 | 操作系统缩放值 | 浏览器缩放值 |
|---|---|---|
| 3840x2160 | 100% | 300% |
| 3840x2160 | 150% | 200% |
| 3840x2160 | 175% | 175% |
| 2560x1440 | 100% | 200% |
| 2560x1440 | 125% | 175% |
| 1920x1080 | 100% | 150% |
| 1366x768 | 100% | 110% |


感谢支持😊

**Comment by FluereL** [comment]
谢谢回复o(*￣▽￣*)ブ 不过放大的体验跟宽屏还是不大一样的，希望之后能够完成适配
