### ISSUE TITLE
分发至 Greasy Fork

### ISSUE THREAD

**Issue by Geeyun-JY3** [wTonyChen/flatnmusic#4]
**描述你所想的解决方案**
Greasy Fork 现已 [支持 UserCSS](https://greasyfork.org/zh-CN/forum/discussion/65484/beta-user-css-support/p1)，希望能将该样式分发至 Greasy Fork。

**Comment by wTonyChen** [comment]
此样式已在 Greasy Fork 分发，并且保持同步更新，感谢你的支持👍

https://greasyfork.org/scripts/406821
