### ISSUE TITLE
顶栏 tab 的圆角有些怪

### ISSUE THREAD

**Issue by Geeyun-JY3** [wTonyChen/flatnmusic#5]
**这个功能请求是否与问题关联？请描述。（可选）**
对整体圆角化每一件，但顶栏 tab（发现应用、我的音乐、朋友）也有圆角后个人感觉有些怪，不知道是不习惯还是怎么的，个人还是倾向于 tab 无圆角。附现最新版（0.6.0） tab 圆角效果图：
![image](https://user-images.githubusercontent.com/49396421/87910493-b2b2e980-ca9c-11ea-9868-6016e0ebd44d.png)

**描述你所想的解决方案**
我个人倾向于这三个 tab 不加圆角

**描述你考虑到的备用方案（可选）**
或者针对这三个 tab 的圆角给个选项？

**附加内容（可选）**
还希望后续能提供一个全局的圆角半径的设置项

**Comment by wTonyChen** [comment]
之前在做这个版本的时候，只是为了界面的一致性，将顶栏的导航加了个圆角。虽然当时有预料到并不是所有人都会接受这个设计，但没想到 Issue 来得这么快。

至于你提到的2个改进:
1. 添加顶栏导航的圆角开关
2. 添加一个全局自定义圆角

第1条，这个将会以“顶栏导航风格”的选项出现在下个版本，并且可能会提供三种不同的风格。

第2条，由于所有的圆角并不是等尺寸的，所以无法进行手动调整。在下个版本，将会提供一个“全局圆角”开关，可以进行全局的圆角关闭。

感谢支持🙏

**Comment by Geeyun-JY3** [comment]
> 之前在做这个版本的时候，只是为了界面的一致性，将顶栏的导航加了个圆角。虽然当时有预料到并不是所有人都会接受这个设计，但没想到 Issue 来得这么快。
> 
> 至于你提到的2个改进:
> 
> 1. 添加顶栏导航的圆角开关
> 2. 添加一个全局自定义圆角
> 
> 第1条，这个将会以“顶栏导航风格”的选项出现在下个版本，并且可能会提供三种不同的风格。
> 
> 第2条，由于所有的圆角并不是等尺寸的，所以无法进行手动调整。在下个版本，将会提供一个“全局圆角”开关，可以进行全局的圆角关闭。
> 
> 感谢支持🙏

了解了，后续方案很棒，我觉得挺好的。
（issue 来的快只是我刚好有空看到更新，实装后感觉有些别扭就顺便反馈了，别紧张，慢慢来也没问题的🙈）

**Comment by wTonyChen** [comment]
现在针对 UserCSS 版本更新的 0.6.1 版本，请尝试下是否符合预期。如仍有问题，请在此继续反馈；如果满意，方可关闭此 Issue。

**感谢支持**

[点此可以直接进行更新](https://raw.githubusercontent.com/wTonyChen/flatnmusic/master/flatnmusic.user.css)

**Comment by Geeyun-JY3** [comment]
可以说是非常满意了。继续加油(ง •̀_•́)ง
