### ISSUE TITLE
关于网站 样式变形，以及样式没有隐藏掉。见图

### ISSUE THREAD

**Issue by Zephyr-Liu** [wTonyChen/flatnmusic#8]
图1：
![ahJyV0.png](https://s1.ax1x.com/2020/08/07/ahJyV0.png)

图2：
![ahJfxJ.png](https://s1.ax1x.com/2020/08/07/ahJfxJ.png)

**Comment by wTonyChen** [comment]
反馈已收到，按钮变形的问题下个更新将会修复

因为目前最新版本测试中，按钮上的字确实不会显示出来。
所以请提供以下详细信息以便确定问题：
1. 使用的浏览器和版本号
2. 安装的什么版本的样式表 (UserCSS或标准版) 或者您在何处安装的样式表
3. 使用的操作系统
4. 您是否使用了浏览器的字体插件或者其他样式有关的修改

感谢支持 :)

**Comment by Zephyr-Liu** [comment]
关于登陆框确实已经修复成功
![a59hkV.png](https://s1.ax1x.com/2020/08/08/a59hkV.png)
但是关于播放栏的问题还是没有解决
![a59OTx.png](https://s1.ax1x.com/2020/08/08/a59OTx.png)
浏览器采用的是Google chrome 版本 84.0.4147.105（正式版本） （64 位）
最新版本样式
Windows操作系统
唯一的是字体样式改变可能是： 
1.油猴脚本的 MacType助手
![a5C96H.png](https://s1.ax1x.com/2020/08/08/a5C96H.png)
2.stylus的 Mac OSX Font Rendering for Windows Based Browsers 样式
![a5CSpD.png](https://s1.ax1x.com/2020/08/08/a5CSpD.png)
3.MacType软件问题
![a5CUc4.png](https://s1.ax1x.com/2020/08/08/a5CUc4.png)
但是我都关闭了测试 发现还是存在这种问题  无奈只能把

**Comment by Zephyr-Liu** [comment]
如果关于Windows版本的话 是Win10专业版 2004版本

**Comment by Zephyr-Liu** [comment]
关于建议：
歌曲播放界面的这个东西能隐藏掉吗？
![a5Psqs.png](https://s1.ax1x.com/2020/08/08/a5Psqs.png)
主界面这个下载客户端能隐藏掉吗 太亮眼了
![a5Psqs.png](https://s1.ax1x.com/2020/08/08/a5Psqs.png)
考虑到或许有人需要下载  但是开发者创建的初心不就是让网页版的网易云收到喜爱吗？
是不是可以考虑隐藏掉呢
当然只是我的建议

**Comment by Zephyr-Liu** [comment]
呃 播放界面的图 上传错了 尴尬
![a5PeV1.png](https://s1.ax1x.com/2020/08/08/a5PeV1.png)

**Comment by wTonyChen** [comment]
## 关于播放栏的文字不隐藏的问题
现在新版已经推出，问题可能已经修复。

如果问题仍然没有解决，请在此 Issue 中回复。

[点此可进行快速更新](https://raw.githubusercontent.com/wTonyChen/flatnmusic/master/flatnmusic.user.css)



## 关于隐藏页面上的下载客户端选项
该功能已经存在，且内置于 Stylus 设置中，您需要手动开启。

1. 点击Stylus 图标，再点击`网易云音乐扁平风格`旁边的齿轮图标
<img src="https://user-images.githubusercontent.com/12113817/89706424-1e9bba00-d998-11ea-977c-0709266e6c56.png" width="270">

2. 找到`隐藏下载选项`，将可见更改为隐藏
<img src="https://user-images.githubusercontent.com/12113817/89706439-3d9a4c00-d998-11ea-96e9-03fbbe94758c.png" width="270">


**如果所有问题已经解决，您可自行关闭此 Issue。**

**Comment by Geeyun-JY3** [comment]
> 呃 播放界面的图 上传错了 尴尬

点开 issue 右上角更多菜单的 `edit` 可以编辑的（小声）

**Comment by Zephyr-Liu** [comment]
成啦 ，开心 谢谢大大

**Comment by wTonyChen** [comment]
既然已经解决的话，我就帮你关闭掉这个 Issue 了 :)
