### ISSUE TITLE
样式不应用于专栏目录页

### ISSUE THREAD

**Issue by Geeyun-JY3** [wTonyChen/flatnmusic#9]
**描述问题**
样式不应用于专栏目录页

**截图（可选）**
![image](https://user-images.githubusercontent.com/49396421/89727405-18204780-da57-11ea-84d0-4d9a509ee6fc.png)

**桌面端 (请完成以下信息)**
 - 操作系统：Windows 10 1909
 - 浏览器：Chrome（百分浏览器）
 - 浏览器版本：4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
 - 显示分辨率：1920x1080
 - 工具：Stylus

**附加内容（可选）**
如：https://music.163.com/#/series?id=2801580 https://music.163.com/#/series?id=6625168
是故意没有在专栏目录页应用样式吗？还是没来得及做？

**Comment by wTonyChen** [comment]
抱歉，这个页面被忽略了，将会在下个更新修复。

感谢支持 :)

**Comment by wTonyChen** [comment]
现在新版本已经推出，问题可能已经修复。如果问题已经修复，您可自行关闭此 Issue。

[更新链接](https://wtonychen.github.io/flatnmusic/flatnmusic.user.css) | [Greasy Fork](https://greasyfork.org/scripts/406821)

感谢支持 :)

**Comment by Geeyun-JY3** [comment]
O 了
